### ISSUE TITLE
Can't click or use anything

### ISSUE THREAD

**Issue by gunar** [cxcorp/cyberpunk2077-hacking-solver#11]
On development environment, I can't click anything because this "backdrop" element is on top of the whole page. 

This fixes it :)

```css
.backdrop { display: none }
```
